#! /bin/sh

# Configuration settings used in caldp container image build scripts

# e.g. export CALDP_IMAGE_REPO=jaytmiller/caldp
export CALDP_IMAGE_REPO=162808325377.dkr.ecr.us-east-1.amazonaws.com/caldp

export CALDP_DEFAULT_TAG=dev
